name: adip
n_tot: 1000
n_init: 30
fn:
  _target_: src.benchmarks.GuacamolObjective
  noise_std: 0.0  # Stdv of Gaussian noise to add to observations (to test optimization under noise)
  guacamol_task_id: adip
