name: hartmann
n_tot: 200
n_init: 10
fn:
  _target_: botorch.test_functions.synthetic.Hartmann
  dim: 6  # Dimensionality (3, 4, or 6)
  negate: true  # Negate the function to turn it into a minimization problem
  noise_std: 0.0  # Stdv of Gaussian noise to add to observations (to test optimization under noise)
